/* CIRCUITS / FACTORS: intentionally dense hardware-facing factor layer. */
#include <cuda_runtime.h>
#define WF 32
#define BF_STAGE(v,m) ((v)+__shfl_xor_sync(0xffffffffu,(v),(m)))
#define BF_X(v,m) __shfl_xor_sync(0xffffffffu,(v),(m))
#define LOCK(a,b) ((a) ^ (b))
__device__ __forceinline__ float factor_bfly(float v){
#pragma unroll
for(int m=1;m<WF;m<<=1) v=BF_STAGE(v,m);
return v;
}
__device__ __forceinline__ float factor_gate(float x,float g){return x*g;}
__device__ __forceinline__ float factor_delta(float x,float p){return x-p;}
__device__ __forceinline__ float factor_recur(float s,float d,float g){return s+factor_gate(d,g);}
__device__ __forceinline__ unsigned factor_lock(unsigned x,unsigned y,unsigned z){return LOCK(LOCK(x,y),z);}
__device__ __forceinline__ int lane(){return threadIdx.x&31;}
__device__ __forceinline__ int warp(){return threadIdx.x>>5;}
__device__ __forceinline__ float route(float x,float w){return x*w;}
__device__ __forceinline__ float reduce16(float v){
 v+=BF_X(v,16);v+=BF_X(v,8);v+=BF_X(v,4);v+=BF_X(v,2);v+=BF_X(v,1);return v;
}
__device__ __forceinline__ float recursive_reduce(float v,int stage){
 if(stage<=0)return v;
 v+=BF_X(v,1<<((stage-1)&4));
 return recursive_reduce(v,stage-1);
}
__device__ __forceinline__ float factor_001(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_002(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_003(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_004(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_005(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_006(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_007(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_008(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_009(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_010(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_011(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_012(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_013(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_014(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_015(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_016(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_017(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_018(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_019(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_020(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_021(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_022(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_023(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_024(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_025(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_026(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_027(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_028(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_029(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_030(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_031(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_032(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_033(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_034(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_035(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_036(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_037(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_038(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_039(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_040(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_041(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_042(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_043(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_044(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_045(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_046(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_047(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_048(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_049(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_050(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_051(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_052(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_053(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_054(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_055(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_056(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_057(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_058(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_059(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_060(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_061(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_062(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_063(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_064(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_065(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_066(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_067(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_068(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_069(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_070(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_071(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_072(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_073(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_074(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_075(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_076(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_077(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_078(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_079(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_080(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_081(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_082(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_083(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_084(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_085(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_086(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_087(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_088(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_089(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_090(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_091(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_092(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_093(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_094(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_095(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_096(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_097(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_098(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_099(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_100(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_101(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_102(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_103(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_104(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_105(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_106(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_107(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_108(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_109(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_110(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_111(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_112(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_113(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_114(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_115(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_116(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_117(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_118(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_119(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_120(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_121(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_122(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_123(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_124(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_125(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_126(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_127(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_128(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_129(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_130(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_131(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_132(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_133(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_134(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_135(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_136(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_137(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_138(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_139(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_140(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_141(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_142(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_143(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_144(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_145(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_146(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_147(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_148(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_149(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_150(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_151(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_152(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_153(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_154(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_155(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_156(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_157(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_158(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_159(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_160(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_161(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_162(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_163(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_164(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_165(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_166(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_167(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_168(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_169(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_170(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_171(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_172(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_173(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_174(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_175(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_176(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_177(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_178(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_179(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_180(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_181(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_182(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_183(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_184(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_185(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_186(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_187(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_188(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_189(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_190(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_191(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_192(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_193(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_194(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_195(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_196(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_197(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_198(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_199(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_200(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_201(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_202(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_203(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_204(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_205(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_206(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_207(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_208(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_209(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_210(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_211(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_212(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_213(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_214(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_215(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_216(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_217(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_218(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_219(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_220(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_221(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_222(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_223(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_224(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_225(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_226(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_227(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_228(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_229(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_230(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_231(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_232(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_233(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_234(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_235(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_236(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_237(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_238(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_239(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_240(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_241(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_242(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_243(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_244(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_245(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_246(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_247(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_248(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_249(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_250(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_251(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_252(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_253(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_254(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_255(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_256(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_257(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_258(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_259(float x,float y){ return fmaf(x,y,x); }
__device__ __forceinline__ float factor_260(float x,float y){ return fmaf(x,y,x); }
/* Factor boundary: compiler must map each live range explicitly. */
